### ISSUE TITLE
Errors after running setup.bash

### ISSUE THREAD

**Issue by dcharrezt** [caelan/LTAMP#1]
Hi,

Is there any particular version of GCC to complete the installation? I tried both python 2.7 and 3.7 with GCC 9.3.

after running `cd control_tools/ik && python setup.py build`

```bash
building 'ikLeft' extension
creating build
creating build/temp.linux-x86_64-3.9
gcc -pthread -B /home/dd/.miniconda3/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/dd/.miniconda3/include -fPIC -O2 -isystem /home/dd/.miniconda3/include -fPIC -I/home/dd/.miniconda3/include/python3.9 -c left_arm_ik.cpp -o build/temp.linux-x86_64-3.9/left_arm_ik.o
In file included from left_arm_ik.cpp:30:
ikfast.h:41:10: fatal error: python2.7/Python.h: No such file or directory
   41 | #include "python2.7/Python.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```

after running `./pddlstream/FastDownward/build.py release64`

```bash
cc1plus: all warnings being treated as errors
make[2]: *** [search/CMakeFiles/downward.dir/build.make:1727: search/CMakeFiles/downward.dir/search_engines/iterated_search.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:123: search/CMakeFiles/downward.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
Traceback (most recent call last):
  File "/home/dd/Projects/LTAMP/./pddlstream/FastDownward/build.py", line 153, in <module>
    main()
  File "/home/dd/Projects/LTAMP/./pddlstream/FastDownward/build.py", line 149, in main
    build(config_name, CONFIGS[config_name], make_parameters)
  File "/home/dd/Projects/LTAMP/./pddlstream/FastDownward/build.py", line 126, in build
    try_run([MAKE] + make_parameters, cwd=build_path)
  File "/home/dd/Projects/LTAMP/./pddlstream/FastDownward/build.py", line 102, in try_run
    subprocess.check_call(cmd, cwd=cwd)
  File "/home/dd/.miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j16']' returned non-zero exit status 2.
```

Thanks a lot!

**Comment by yuecao1997** [comment]
Hi, gcc 8.4 works for me.

**Comment by dcharrezt** [comment]
Hi, Thanks setting GCC to 8.4 worked!
